CREATE TABLE APK_INFO
(
   APK_NAME              VARCHAR(128) NULL,
   APK_SIZE              VARCHAR(128) NULL,
   UPLOAD_DATE           VARCHAR(128) NULL,
   MD5                   VARCHAR(128) NULL,
   SHA_1                 VARCHAR(128) NULL,
   CRC32                 VARCHAR(128) NULL,
   CASE_ID               VARCHAR(128) NOT NULL,
   M_ID                  CHAR(18) NOT NULL
)
;



ALTER TABLE APK_INFO
   ADD  PRIMARY KEY (APK_NAME,CASE_ID,M_ID)
;



CREATE TABLE APK_XML
(
   XML_DATA              VARCHAR(128) NULL,
   PERMISSION            VARCHAR(128) NULL,
   CASE_ID               VARCHAR(128) NOT NULL,
   M_ID                  CHAR(18) NOT NULL
)
;



ALTER TABLE APK_XML
   ADD  PRIMARY KEY (CASE_ID,M_ID)
;



CREATE TABLE ARTIFACT_INFO
(
   A_ID                  VARCHAR(128) NULL,
   A_DOMAIN              VARCHAR(128) NULL,
   A_MAIL                VARCHAR(128) NULL,
   A_PHONE               VARCHAR(128) NULL,
   A_IP                  VARCHAR(128) NULL,
   A_PW                  VARCHAR(128) NULL,
   CASE_ID               VARCHAR(128) NOT NULL,
   M_ID                  CHAR(18) NOT NULL
)
;



ALTER TABLE ARTIFACT_INFO
   ADD  PRIMARY KEY (A_ID,CASE_ID,M_ID)
;



CREATE TABLE CASE_INFO
(
   CASE_ID               VARCHAR(128) NULL,
   CASE_DATE             VARCHAR(128) NULL,
   A_ID                  VARCHAR(128) NULL,
   M_CODE                VARCHAR(128) NULL,
   M_ID                  CHAR(18) NULL
)
;

# 회원 전용...
CREATE TABLE HISTORY
(
   M_CODE  VARCHAR(128) NOT NULL PRIMARY KEY
   CASE_ID INT NOT NULL AUTO_INCREMENT
)


ALTER TABLE CASE_INFO
   ADD  PRIMARY KEY (CASE_ID,M_ID)
;



CREATE TABLE MEMBER
(
   M_ID                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   M_PW                  VARCHAR(128) NOT NULL,
   M_MAIL                VARCHAR(128) NULL,
   M_CODE                VARCHAR(128) NULL
);



ALTER TABLE MEMBER
   ADD  PRIMARY KEY (M_ID)
;



ALTER TABLE APK_INFO
   ADD FOREIGN KEY R_3 (CASE_ID,M_ID) REFERENCES CASE_INFO(CASE_ID,M_ID)
;



ALTER TABLE APK_XML
   ADD FOREIGN KEY R_4 (CASE_ID,M_ID) REFERENCES CASE_INFO(CASE_ID,M_ID)
;



ALTER TABLE ARTIFACT_INFO
   ADD FOREIGN KEY R_2 (CASE_ID,M_ID) REFERENCES CASE_INFO