CREATE TABLE MEMBER
(
   M_ID                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   M_PW                  VARCHAR(128) NOT NULL,
   M_MAIL                VARCHAR(128) NULL,
   M_CODE                VARCHAR(128) NULL
);

# member use only, non-member is search apk or case with APK_HASH
# Anonymous member : JohnDoe
CREATE TABLE CASE_LIST
(
   M_CODE  VARCHAR(128) NOT NULL PRIMARY KEY
   CASE_ID VARCHAR(128) NOT NULL
);

# Non member is reference with APK_HASH_SHA1
CREATE TABLE CASE_INFO
(
   CASE_ID               VARCHAR(128) NOT NULL PRIMARY KEY,
   ARTIFACT_ID           VARCHAR(128) NOT NULL
);

CREATE TABLE ARTIFACT_INFO
(
   ARTIFACT_ID           VARCHAR(128) NOT NULL PRIMARY KEY,
   PERMISSION_ARTIFACT TEXT NULL,
   DOMAIN_ARTIFACT TEXT NULL,
   MAIL_ARTIFACT TEXT NULL,
   ADDRESS_ARTIFACT TEXT NULL,
   PHONE_ARTIFACT TEXT NULL,
   ETC_ARTIFACT TEXT NULL
);

CREATE TABLE APK_INFO
(
	CASE_ID VARCHAR(128) NOT NULL PRIMARY KEY,
	APK_NAME VARCHAR(255) NOT NULL,
	APK_SIZE INT NOT NULL,
	APK_HASH_MD5 VARCHAR(32) NOT NULL,
	APK_HASH_SHA1 VARCHAR(20) NOT NULL
);